[[1;34mINFO[m] Scanning for projects...
[[1;33mWARNING[m] 
[[1;33mWARNING[m] Some problems were encountered while building the effective model for org.apache.hadoop:hadoop-common:jar:3.3.3
[[1;33mWARNING[m] 'dependencyManagement.dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.apache.hbase:hbase-server:jar -> duplicate declaration of version ${hbase.version} @ org.apache.hadoop:hadoop-project:3.3.3, /home/shuai/xlab/cfuzz/fuzz-hadoop/hadoop-project/pom.xml, line 1691, column 19
[[1;33mWARNING[m] 
[[1;33mWARNING[m] It is highly recommended to fix these problems because they threaten the stability of your build.
[[1;33mWARNING[m] 
[[1;33mWARNING[m] For this reason, future Maven versions might no longer support building such malformed projects.
[[1;33mWARNING[m] 
[[1;34mINFO[m] ------------------------------------------------------------------------
[[1;34mINFO[m] Detecting the operating system and CPU architecture
[[1;34mINFO[m] ------------------------------------------------------------------------
[[1;34mINFO[m] os.detected.name: linux
[[1;34mINFO[m] os.detected.arch: x86_64
[[1;34mINFO[m] os.detected.version: 5.10
[[1;34mINFO[m] os.detected.version.major: 5
[[1;34mINFO[m] os.detected.version.minor: 10
[[1;34mINFO[m] os.detected.release: ubuntu
[[1;34mINFO[m] os.detected.release.version: 20.04
[[1;34mINFO[m] os.detected.release.like.ubuntu: true
[[1;34mINFO[m] os.detected.release.like.debian: true
[[1;34mINFO[m] os.detected.classifier: linux-x86_64
[[1;34mINFO[m] 
[[1;34mINFO[m] [1m------------------< [0;36morg.apache.hadoop:hadoop-common[0;1m >-------------------[m
[[1;34mINFO[m] [1mBuilding Apache Hadoop Common 3.3.3[m
[[1;34mINFO[m] [1m--------------------------------[ jar ]---------------------------------[m
[[1;34mINFO[m] 
[[1;34mINFO[m] [1m--- [0;32mjqf-maven-plugin:2.0-SNAPSHOT:fuzz[m [1m(default-cli)[m @ [36mhadoop-common[0;1m ---[m
Set Maven-Surefire-Plugin Configuration
[[1;34mINFO[m] Using port 63074
[[1;34mINFO[m] STARTING testGracefulFailoverMultipleZKfcsFuzz
[[1;34mINFO[m] STARTING server
[[1;34mINFO[m] Server environment:zookeeper.version=3.5.6-c11b7e26bc554b8523dc929761dd28808913f091, built on 10/08/2019 20:18 GMT
[[1;34mINFO[m] Server environment:host.name=KingsLand
[[1;34mINFO[m] Server environment:java.version=11.0.15
[[1;34mINFO[m] Server environment:java.vendor=Private Build
[[1;34mINFO[m] Server environment:java.home=/usr/lib/jvm/java-11-openjdk-amd64
[[1;34mINFO[m] Server environment:java.class.path=/usr/share/maven/boot/plexus-classworlds-2.x.jar
[[1;34mINFO[m] Server environment:java.library.path=/usr/java/packages/lib:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib
[[1;34mINFO[m] Server environment:java.io.tmpdir=/tmp
[[1;34mINFO[m] Server environment:java.compiler=<NA>
[[1;34mINFO[m] Server environment:os.name=Linux
[[1;34mINFO[m] Server environment:os.arch=amd64
[[1;34mINFO[m] Server environment:os.version=5.10.0-1050-oem
[[1;34mINFO[m] Server environment:user.name=shuai
[[1;34mINFO[m] Server environment:user.home=/home/shuai
[[1;34mINFO[m] Server environment:user.dir=/home/shuai/xlab/cfuzz/fuzz-hadoop/hadoop-common-project/hadoop-common
[[1;34mINFO[m] Server environment:os.memory.free=318MB
[[1;34mINFO[m] Server environment:os.memory.max=7960MB
[[1;34mINFO[m] Server environment:os.memory.total=502MB
[[1;34mINFO[m] zookeeper.snapshot.trust.empty : false
[[1;34mINFO[m] zookeeper.snapshotSizeFactor = 0.33
[[1;34mINFO[m] minSessionTimeout set to 6000
[[1;34mINFO[m] maxSessionTimeout set to 60000
[[1;34mINFO[m] Created server with tickTime 3000 minSessionTimeout 6000 maxSessionTimeout 60000 datadir /home/shuai/xlab/cfuzz/fuzz-hadoop/hadoop-common-project/hadoop-common/target/test/data/test17483812831299709283.junit.dir/version-2 snapdir /home/shuai/xlab/cfuzz/fuzz-hadoop/hadoop-common-project/hadoop-common/target/test/data/test17483812831299709283.junit.dir/version-2
[[1;34mINFO[m] Using org.apache.zookeeper.server.NIOServerCnxnFactory as server connection factory
[[1;34mINFO[m] Configuring NIO connection handler with 10s sessionless connection timeout, 2 selector thread(s), 32 worker threads, and 64 kB direct buffers.
[[1;34mINFO[m] binding to port 0.0.0.0/0.0.0.0:63074
[[1;34mINFO[m] Snapshotting: 0x0 to /home/shuai/xlab/cfuzz/fuzz-hadoop/hadoop-common-project/hadoop-common/target/test/data/test17483812831299709283.junit.dir/version-2/snapshot.0
[[1;34mINFO[m] Snapshotting: 0x0 to /home/shuai/xlab/cfuzz/fuzz-hadoop/hadoop-common-project/hadoop-common/target/test/data/test17483812831299709283.junit.dir/version-2/snapshot.0
[[1;34mINFO[m] connecting to 127.0.0.1 63074
[[1;34mINFO[m] The list of known four letter word commands is : [{1936881266=srvr, 1937006964=stat, 2003003491=wchc, 1685417328=dump, 1668445044=crst, 1936880500=srst, 1701738089=envi, 1668247142=conf, -720899=telnet close, 2003003507=wchs, 2003003504=wchp, 1684632179=dirs, 1668247155=cons, 1835955314=mntr, 1769173615=isro, 1920298859=ruok, 1735683435=gtmk, 1937010027=stmk}]
[[1;34mINFO[m] The list of enabled four letter word commands is : [[wchs, stat, wchp, dirs, stmk, conf, ruok, mntr, srvr, wchc, envi, srst, isro, dump, gtmk, telnet close, crst, cons]]
[[1;34mINFO[m] Processing stat command from /127.0.0.1:47160
[[1;34mINFO[m] Stat command output
[[1;34mINFO[m] Client test setup finished
[[1;33mWARNING[m] Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[[1;34mINFO[m] Client environment:zookeeper.version=3.5.6-c11b7e26bc554b8523dc929761dd28808913f091, built on 10/08/2019 20:18 GMT
[[1;34mINFO[m] Client environment:host.name=KingsLand
[[1;34mINFO[m] Client environment:java.version=11.0.15
[[1;34mINFO[m] Client environment:java.vendor=Private Build
[[1;34mINFO[m] Client environment:java.home=/usr/lib/jvm/java-11-openjdk-amd64
[[1;34mINFO[m] Client environment:java.class.path=/usr/share/maven/boot/plexus-classworlds-2.x.jar
[[1;34mINFO[m] Client environment:java.library.path=/usr/java/packages/lib:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib
[[1;34mINFO[m] Client environment:java.io.tmpdir=/tmp
[[1;34mINFO[m] Client environment:java.compiler=<NA>
[[1;34mINFO[m] Client environment:os.name=Linux
[[1;34mINFO[m] Client environment:os.arch=amd64
[[1;34mINFO[m] Client environment:os.version=5.10.0-1050-oem
[[1;34mINFO[m] Client environment:user.name=shuai
[[1;34mINFO[m] Client environment:user.home=/home/shuai
[[1;34mINFO[m] Client environment:user.dir=/home/shuai/xlab/cfuzz/fuzz-hadoop/hadoop-common-project/hadoop-common
[[1;34mINFO[m] Client environment:os.memory.free=219MB
[[1;34mINFO[m] Client environment:os.memory.max=7960MB
[[1;34mINFO[m] Client environment:os.memory.total=502MB
[[1;34mINFO[m] Initiating client connection, connectString=127.0.0.1:63074 sessionTimeout=10000 watcher=org.apache.hadoop.ha.ActiveStandbyElector$WatcherWithClientRef@42b34def
[[1;34mINFO[m] Setting -D jdk.tls.rejectClientInitiatedRenegotiation=true to disable client-initiated TLS renegotiation
[[1;34mINFO[m] jute.maxbuffer value is 4194304 Bytes
[[1;34mINFO[m] zookeeper.request.timeout value is 0. feature enabled=
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket connection established, initiating session, client: /127.0.0.1:47182, server: localhost/127.0.0.1:63074
[[1;34mINFO[m] Creating new log file: log.1
[[1;34mINFO[m] Session establishment complete on server localhost/127.0.0.1:63074, sessionid = 0x1020c9466840000, negotiated timeout = 10000
[[1;34mINFO[m] Session connected.
[[1;34mINFO[m] got auth packet /127.0.0.1:47182
[[1;34mINFO[m] auth success /127.0.0.1:47182
[[1;34mINFO[m] Successfully created /hadoop-ha/dummy-cluster in ZK.
[[1;34mINFO[m] Session: 0x1020c9466840000 closed
[[1;33mWARNING[m] Ignoring stale result from old client with sessionId 0x1020c9466840000
[[1;34mINFO[m] Waiting for svc0 to enter active state
[[1;34mINFO[m] EventThread shut down for session: 0x1020c9466840000
[[1;34mINFO[m] Initiating client connection, connectString=127.0.0.1:63074 sessionTimeout=10000 watcher=org.apache.hadoop.ha.ActiveStandbyElector$WatcherWithClientRef@1a616315
[[1;34mINFO[m] jute.maxbuffer value is 4194304 Bytes
[[1;34mINFO[m] zookeeper.request.timeout value is 0. feature enabled=
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket connection established, initiating session, client: /127.0.0.1:47184, server: localhost/127.0.0.1:63074
[[1;34mINFO[m] Session establishment complete on server localhost/127.0.0.1:63074, sessionid = 0x1020c9466840001, negotiated timeout = 10000
[[1;34mINFO[m] Session connected.
[[1;34mINFO[m] got auth packet /127.0.0.1:47184
[[1;34mINFO[m] auth success /127.0.0.1:47184
[[1;34mINFO[m] ZKFC RpcServer binding to 0.0.0.0/0.0.0.0:0
[[1;34mINFO[m] Using callQueue: class java.util.concurrent.LinkedBlockingQueue, queueCapacity: 300, scheduler: class org.apache.hadoop.ipc.DefaultRpcScheduler, ipcBackoff: false.
[[1;34mINFO[m] Starting Socket Reader #1 for port 0
[[1;34mINFO[m] IPC Server Responder: starting
[[1;34mINFO[m] IPC Server listener on 0: starting
[[1;34mINFO[m] Entering state SERVICE_HEALTHY
[[1;34mINFO[m] Local service DummyHAService #1 entered state: SERVICE_HEALTHY
[[1;34mINFO[m] Checking for any old active which needs to be fenced...
[[1;34mINFO[m] No old node to fence
[[1;34mINFO[m] Writing znode /hadoop-ha/dummy-cluster/ActiveBreadCrumb to indicate that the local node is the most recent active...
[[1;34mINFO[m] Trying to make DummyHAService #1 active...
[[1;34mINFO[m] Successfully transitioned DummyHAService #1 to active state
[[1;34mINFO[m] Adding svc1
[[1;34mINFO[m] Initiating client connection, connectString=127.0.0.1:63074 sessionTimeout=10000 watcher=org.apache.hadoop.ha.ActiveStandbyElector$WatcherWithClientRef@51ceab28
[[1;34mINFO[m] jute.maxbuffer value is 4194304 Bytes
[[1;34mINFO[m] zookeeper.request.timeout value is 0. feature enabled=
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket connection established, initiating session, client: /127.0.0.1:47190, server: localhost/127.0.0.1:63074
[[1;34mINFO[m] Session establishment complete on server localhost/127.0.0.1:63074, sessionid = 0x1020c9466840002, negotiated timeout = 10000
[[1;34mINFO[m] Session connected.
[[1;34mINFO[m] got auth packet /127.0.0.1:47190
[[1;34mINFO[m] auth success /127.0.0.1:47190
[[1;34mINFO[m] ZKFC RpcServer binding to 0.0.0.0/0.0.0.0:0
[[1;34mINFO[m] Using callQueue: class java.util.concurrent.LinkedBlockingQueue, queueCapacity: 300, scheduler: class org.apache.hadoop.ipc.DefaultRpcScheduler, ipcBackoff: false.
[[1;34mINFO[m] Starting Socket Reader #1 for port 0
[[1;34mINFO[m] IPC Server Responder: starting
[[1;34mINFO[m] IPC Server listener on 0: starting
[[1;34mINFO[m] Entering state SERVICE_HEALTHY
[[1;34mINFO[m] Local service DummyHAService #2 entered state: SERVICE_HEALTHY
[[1;34mINFO[m] ZK Election indicated that DummyHAService #2 should become standby
[[1;34mINFO[m] Successfully transitioned DummyHAService #2 to standby state
[[1;34mINFO[m] Adding svc2
[[1;34mINFO[m] Initiating client connection, connectString=127.0.0.1:63074 sessionTimeout=10000 watcher=org.apache.hadoop.ha.ActiveStandbyElector$WatcherWithClientRef@341f8be5
[[1;34mINFO[m] jute.maxbuffer value is 4194304 Bytes
[[1;34mINFO[m] zookeeper.request.timeout value is 0. feature enabled=
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket connection established, initiating session, client: /127.0.0.1:47192, server: localhost/127.0.0.1:63074
[[1;34mINFO[m] Session establishment complete on server localhost/127.0.0.1:63074, sessionid = 0x1020c9466840003, negotiated timeout = 10000
[[1;34mINFO[m] Session connected.
[[1;34mINFO[m] got auth packet /127.0.0.1:47192
[[1;34mINFO[m] auth success /127.0.0.1:47192
[[1;34mINFO[m] ZKFC RpcServer binding to 0.0.0.0/0.0.0.0:0
[[1;34mINFO[m] Using callQueue: class java.util.concurrent.LinkedBlockingQueue, queueCapacity: 300, scheduler: class org.apache.hadoop.ipc.DefaultRpcScheduler, ipcBackoff: false.
[[1;34mINFO[m] Starting Socket Reader #1 for port 0
[[1;34mINFO[m] IPC Server Responder: starting
[[1;34mINFO[m] IPC Server listener on 0: starting
[[1;34mINFO[m] Entering state SERVICE_HEALTHY
[[1;34mINFO[m] Local service DummyHAService #3 entered state: SERVICE_HEALTHY
[[1;34mINFO[m] ZK Election indicated that DummyHAService #3 should become standby
[[1;34mINFO[m] Successfully transitioned DummyHAService #3 to standby state
[[1;34mINFO[m] Asking DummyHAService #3 to cede its active state for 10000ms
[[1;34mINFO[m] Requested by shuai (auth:SIMPLE) at null to cede active role.
[[1;34mINFO[m] Successfully ensured local node is in standby mode
[[1;34mINFO[m] Yielding from election
[[1;34mINFO[m] Session: 0x1020c9466840003 closed
[[1;34mINFO[m] Would have joined master election, but this node is prohibited from doing so for 9895 more ms
[[1;34mINFO[m] Asking DummyHAService #1 to cede its active state for 10000ms
[[1;33mWARNING[m] Ignoring stale result from old client with sessionId 0x1020c9466840003
[[1;34mINFO[m] EventThread shut down for session: 0x1020c9466840003
[[1;34mINFO[m] Requested by shuai (auth:SIMPLE) at null to cede active role.
[[1;34mINFO[m] Successfully ensured local node is in standby mode
[[1;34mINFO[m] Yielding from election
[[1;34mINFO[m] Deleting bread-crumb of active node...
[[1;34mINFO[m] Checking for any old active which needs to be fenced...
[[1;34mINFO[m] No old node to fence
[[1;34mINFO[m] Writing znode /hadoop-ha/dummy-cluster/ActiveBreadCrumb to indicate that the local node is the most recent active...
[[1;34mINFO[m] Trying to make DummyHAService #2 active...
[[1;34mINFO[m] Successfully transitioned DummyHAService #2 to active state
[[1;34mINFO[m] Session: 0x1020c9466840001 closed
[[1;34mINFO[m] Would have joined master election, but this node is prohibited from doing so for 9890 more ms
[[1;33mWARNING[m] Ignoring stale result from old client with sessionId 0x1020c9466840001
[[1;34mINFO[m] Initiating client connection, connectString=127.0.0.1:63074 sessionTimeout=10000 watcher=org.apache.hadoop.ha.ActiveStandbyElector$WatcherWithClientRef@30c9509c
[[1;33mWARNING[m] Ignoring stale result from old client with sessionId 0x1020c9466840001
[[1;34mINFO[m] EventThread shut down for session: 0x1020c9466840001
[[1;34mINFO[m] jute.maxbuffer value is 4194304 Bytes
[[1;34mINFO[m] zookeeper.request.timeout value is 0. feature enabled=
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket connection established, initiating session, client: /127.0.0.1:47200, server: localhost/127.0.0.1:63074
[[1;34mINFO[m] Session establishment complete on server localhost/127.0.0.1:63074, sessionid = 0x1020c9466840004, negotiated timeout = 10000
[[1;34mINFO[m] Session connected.
[[1;34mINFO[m] Initiating client connection, connectString=127.0.0.1:63074 sessionTimeout=10000 watcher=org.apache.hadoop.ha.ActiveStandbyElector$WatcherWithClientRef@69cf12b8
[[1;34mINFO[m] got auth packet /127.0.0.1:47200
[[1;34mINFO[m] jute.maxbuffer value is 4194304 Bytes
[[1;34mINFO[m] auth success /127.0.0.1:47200
[[1;34mINFO[m] zookeeper.request.timeout value is 0. feature enabled=
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket connection established, initiating session, client: /127.0.0.1:47202, server: localhost/127.0.0.1:63074
[[1;34mINFO[m] ZK Election indicated that DummyHAService #3 should become standby
[[1;34mINFO[m] Successfully transitioned DummyHAService #3 to standby state
[[1;34mINFO[m] Session establishment complete on server localhost/127.0.0.1:63074, sessionid = 0x1020c9466840005, negotiated timeout = 10000
[[1;34mINFO[m] Session connected.
[[1;34mINFO[m] Successfully became active. Successfully transitioned DummyHAService #2 to active state
[[1;34mINFO[m] got auth packet /127.0.0.1:47202
[[1;34mINFO[m] auth success /127.0.0.1:47202
[[1;34mINFO[m] ZK Election indicated that DummyHAService #1 should become standby
[[1;34mINFO[m] Asking DummyHAService #1 to cede its active state for 10000ms
[[1;34mINFO[m] Successfully transitioned DummyHAService #1 to standby state
[[1;34mINFO[m] Requested by shuai (auth:SIMPLE) at null to cede active role.
[[1;34mINFO[m] Successfully ensured local node is in standby mode
[[1;34mINFO[m] Yielding from election
[[1;34mINFO[m] Session: 0x1020c9466840005 closed
[[1;34mINFO[m] Would have joined master election, but this node is prohibited from doing so for 9898 more ms
[[1;34mINFO[m] Asking DummyHAService #2 to cede its active state for 10000ms
[[1;33mWARNING[m] Ignoring stale result from old client with sessionId 0x1020c9466840005
[[1;33mWARNING[m] Ignoring stale result from old client with sessionId 0x1020c9466840005
[[1;34mINFO[m] Requested by shuai (auth:SIMPLE) at null to cede active role.
[[1;34mINFO[m] EventThread shut down for session: 0x1020c9466840005
[[1;34mINFO[m] Successfully ensured local node is in standby mode
[[1;34mINFO[m] Yielding from election
[[1;34mINFO[m] Deleting bread-crumb of active node...
[[1;34mINFO[m] Checking for any old active which needs to be fenced...
[[1;34mINFO[m] No old node to fence
[[1;34mINFO[m] Writing znode /hadoop-ha/dummy-cluster/ActiveBreadCrumb to indicate that the local node is the most recent active...
[[1;34mINFO[m] Trying to make DummyHAService #3 active...
[[1;34mINFO[m] Successfully transitioned DummyHAService #3 to active state
[[1;34mINFO[m] Session: 0x1020c9466840002 closed
[[1;34mINFO[m] Would have joined master election, but this node is prohibited from doing so for 9886 more ms
[[1;33mWARNING[m] Ignoring stale result from old client with sessionId 0x1020c9466840002
[[1;34mINFO[m] Initiating client connection, connectString=127.0.0.1:63074 sessionTimeout=10000 watcher=org.apache.hadoop.ha.ActiveStandbyElector$WatcherWithClientRef@5af15de7
[[1;33mWARNING[m] Ignoring stale result from old client with sessionId 0x1020c9466840002
[[1;34mINFO[m] jute.maxbuffer value is 4194304 Bytes
[[1;34mINFO[m] EventThread shut down for session: 0x1020c9466840002
[[1;34mINFO[m] zookeeper.request.timeout value is 0. feature enabled=
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket connection established, initiating session, client: /127.0.0.1:47206, server: localhost/127.0.0.1:63074
[[1;34mINFO[m] Session establishment complete on server localhost/127.0.0.1:63074, sessionid = 0x1020c9466840006, negotiated timeout = 10000
[[1;34mINFO[m] Session connected.
[[1;34mINFO[m] Initiating client connection, connectString=127.0.0.1:63074 sessionTimeout=10000 watcher=org.apache.hadoop.ha.ActiveStandbyElector$WatcherWithClientRef@5565054d
[[1;34mINFO[m] got auth packet /127.0.0.1:47206
[[1;34mINFO[m] jute.maxbuffer value is 4194304 Bytes
[[1;34mINFO[m] auth success /127.0.0.1:47206
[[1;34mINFO[m] zookeeper.request.timeout value is 0. feature enabled=
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket connection established, initiating session, client: /127.0.0.1:47208, server: localhost/127.0.0.1:63074
[[1;34mINFO[m] ZK Election indicated that DummyHAService #1 should become standby
[[1;34mINFO[m] Session establishment complete on server localhost/127.0.0.1:63074, sessionid = 0x1020c9466840007, negotiated timeout = 10000
[[1;34mINFO[m] Successfully transitioned DummyHAService #1 to standby state
[[1;34mINFO[m] Successfully became active. Successfully transitioned DummyHAService #3 to active state
[[1;34mINFO[m] Session connected.
[[1;34mINFO[m] got auth packet /127.0.0.1:47208
[[1;34mINFO[m] auth success /127.0.0.1:47208
[[1;34mINFO[m] Asking DummyHAService #2 to cede its active state for 10000ms
[[1;34mINFO[m] Requested by shuai (auth:SIMPLE) at null to cede active role.
[[1;34mINFO[m] Successfully ensured local node is in standby mode
[[1;34mINFO[m] Yielding from election
[[1;34mINFO[m] Session: 0x1020c9466840007 closed
[[1;34mINFO[m] Would have joined master election, but this node is prohibited from doing so for 9898 more ms
[[1;34mINFO[m] Asking DummyHAService #3 to cede its active state for 10000ms
[[1;33mWARNING[m] Ignoring stale result from old client with sessionId 0x1020c9466840007
[[1;34mINFO[m] Requested by shuai (auth:SIMPLE) at null to cede active role.
[[1;33mWARNING[m] Ignoring stale result from old client with sessionId 0x1020c9466840007
[[1;34mINFO[m] Successfully ensured local node is in standby mode
[[1;34mINFO[m] EventThread shut down for session: 0x1020c9466840007
[[1;34mINFO[m] Yielding from election
[[1;34mINFO[m] Deleting bread-crumb of active node...
[[1;34mINFO[m] Checking for any old active which needs to be fenced...
[[1;34mINFO[m] No old node to fence
[[1;34mINFO[m] Writing znode /hadoop-ha/dummy-cluster/ActiveBreadCrumb to indicate that the local node is the most recent active...
[[1;34mINFO[m] Trying to make DummyHAService #1 active...
[[1;34mINFO[m] Successfully transitioned DummyHAService #1 to active state
[[1;34mINFO[m] Session: 0x1020c9466840004 closed
[[1;34mINFO[m] Would have joined master election, but this node is prohibited from doing so for 9895 more ms
[[1;33mWARNING[m] Ignoring stale result from old client with sessionId 0x1020c9466840004
[[1;34mINFO[m] Initiating client connection, connectString=127.0.0.1:63074 sessionTimeout=10000 watcher=org.apache.hadoop.ha.ActiveStandbyElector$WatcherWithClientRef@167803c3
[[1;33mWARNING[m] Ignoring stale result from old client with sessionId 0x1020c9466840004
[[1;34mINFO[m] EventThread shut down for session: 0x1020c9466840004
[[1;34mINFO[m] jute.maxbuffer value is 4194304 Bytes
[[1;34mINFO[m] zookeeper.request.timeout value is 0. feature enabled=
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket connection established, initiating session, client: /127.0.0.1:47212, server: localhost/127.0.0.1:63074
[[1;34mINFO[m] Session establishment complete on server localhost/127.0.0.1:63074, sessionid = 0x1020c9466840008, negotiated timeout = 10000
[[1;34mINFO[m] Session connected.
[[1;34mINFO[m] Initiating client connection, connectString=127.0.0.1:63074 sessionTimeout=10000 watcher=org.apache.hadoop.ha.ActiveStandbyElector$WatcherWithClientRef@35003b09
[[1;34mINFO[m] got auth packet /127.0.0.1:47212
[[1;34mINFO[m] jute.maxbuffer value is 4194304 Bytes
[[1;34mINFO[m] auth success /127.0.0.1:47212
[[1;34mINFO[m] zookeeper.request.timeout value is 0. feature enabled=
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket connection established, initiating session, client: /127.0.0.1:47214, server: localhost/127.0.0.1:63074
[[1;34mINFO[m] ZK Election indicated that DummyHAService #2 should become standby
[[1;34mINFO[m] Session establishment complete on server localhost/127.0.0.1:63074, sessionid = 0x1020c9466840009, negotiated timeout = 10000
[[1;34mINFO[m] Successfully transitioned DummyHAService #2 to standby state
[[1;34mINFO[m] Successfully became active. Successfully transitioned DummyHAService #1 to active state
[[1;34mINFO[m] Session connected.
[[1;34mINFO[m] got auth packet /127.0.0.1:47214
[[1;34mINFO[m] auth success /127.0.0.1:47214
[[1;31mERROR[m] The failover controller encounters runtime error: 
[[1;31mERROR[m] The failover controller encounters[ 1r;31umnjava.lang.Intteime error: 
rrupte[[1[;3d1Emxjava.lang.In1te;r3rup1temcEdRROEexpcteipotn[mR[imo]n T[hm

e failover controller encounters   r      untime error: 
[1;31m[[1mat[m1majtav[am.lang.InterruptedException[m
     [ 1jmaatv[amj ajvaav.laan.gl.Object.wait.laanngg..OObbjjeecctt..wwaaiitt ( ([1mNa tive Method[m)[1mNati
v e   M ethod[1[m(at[1[mm) 
j a v a .la[n1gmat[mm N.aOtbijveect jMaveth.owda[ima).
l t   ang.Object.wait[1mat[m java.lang.Object.wait [[1; 3(4mINFO[m] ZK Election in d(i[cated that DummyHAService #3 should become standby
[1mObject.java:328[m)(
 [ 1 m Object[1m1atm.[jmO boarva:328[m)
    je[c1tm.at[m org.apache.hadoop.ha.ZKFailoverController.mainLoopg.ajpaavca :([1mZKFailoverController.hjea.vha:a3d8o9op[.mh)a
. 3 2 8 [m)
    Z[KFailoverController.mainLoop[1mat[m1 mo rg.apacaht[me.hadoop.ha.ZKFailoverController.doRun([1 m(Z KFailoverController.java:389[m)o
rg.[a1pache.hadoop.ha.ZKFailoverControll[[1;34mINFO[m] Succ essfully transitioned DummyHAService #3 to standby statee
r.mainLoopmZKFailover C(ontroller.java:253[m)
     [1mat[m org.apache.hadoop.ha.ZKFailoverCo[n1mZKFailoverController.java:3 89 [m)
[ t r  oll[e1rm1amtat[m org.apache.hadoop.ha..acZcKeFsasiloverController.doRun[m org.apache.hadoop.h$00 ([a1mZKFailoverControll0er.java:253[m).
 ([ 1  m ZKFai[l1omvaetr[m ZoKrController.gjava:63[m)F
ai    .alpacohe.hadoop.ha.ZKFailoverController.access$000[1mat[mv eorC on(trroller.doRun[1mZK g(.aF[1maZKFailoverController.java:253[m)
p  a  c[1mat[m org.apache.hadoop.ha.ZKFailoverController.access$000il o(v[1mhZeKerContFraoiloverController.java:63[m).
 h aldloer.java:63[m) 
   [ 1 matop.ha[.mZ [o1rmg.apache.KFailohvaedoopa.ha.ZKFailoverContrroClolner$1.runt[mt  o(rg.apache.hadoop.ha.ZKFailoverController$1.runroller$1[.1runmZKFailoverContr  ((ol[1mZKFailoverController.java:[181[m)l
 1  m ZKFa[e1mri.lojvaevra:181[m)
    atCo[m org.apache.hadoop.ha.ZKFail[1mat[mo voerrCgo.ntranptarolollelcerh$1.runr.java:1 81[m)
e . h(a[1dmZK Fa il[o1verController.java:177[m)o
op m a  t.ha.ZKFailover[C1omnat[[mm tororg.apache.hadoop.ha.ZKFailoverController$1.run org.apache .lhlaerd$(1[.1runmZKFailoverCont r(ol[l1meoop.securirt.yj.ZSKeFcurityUtil.doAsLoginUserOrFatalavaa:177 [([1mSecurityUtil.java:503[m)i
loverConm)t
r        [1mat[[m1 morg.aatpaoclhe.hadoop.ha.ZKFailoverController.run[ml e r.jav(a:[117mZKFailoverController.java:177[m)
    [1mat[morg.ap aorg.ap7acchhee.hadoop.ha.MiniZKFCCluster$DummyZKFCThread.doWork[m)
. (h a d o o[p.[s1me1cmuatri[tmy.SecuMriityUti lonrgi.aZpKaF.doAsLoginUserOrFCaCtalche.hadoop.security.Secluurster.java:301[m) ([1mSecu
r  i t y[U1tmiattyU[mt oiril.java:503[mg).
a pache.hadoop.test.MultithreadedTestUtil$TestingThread.runl.doAsLoginUserOrFatal    ([1mMultithreadedTestUtil.java:189[m)
 ([1mSecurityUtil.java:503[m)
  [1mat  [[1mat[m org.apache.hadoom org.apap.ha.ZKFai[l[o1v;34mINFO[m] Stopping server on 33613
cheer.Choantroller.rundoop.ha.ZKFailoverCon tro(ll[e1rm.ruZnKFailoverControlle (r[1mZKF.ajialvoaverContro:ller.java:177[m)
1 7 7  [1[mma)t
 [ m   or[g1.maapt[m org.apache.hadoop.hache.hadoo[[1;34mINFO[m] Stopping IPC Server lisptener on 0
a.Min[[1;34.mha.MiiZnINFO[m] Stopping IPC Server RespondeiZKFCClustKFCCluster$DummyZKFCThrer$DummyZr
KFCT[ead.doWorkhread.[d1oWork ([1m;34mINMFiOni[ZmK (FCCluster.java:301][ mY)i
    eldin[g1 mfrom election
[1mMinaiZKFCCluster.java:301[m)t
 [ m   org[.1ampachea.tha[dmoo po.rtge.apachset..MultithreadedTestUtil$TehsatdiongThread.runop.test.MultithreadedTestUtil$TestingThread.run ([1mMultithreadedT ([1emsMtuUlttiilt.hjraevaad:189[m)
edTestUtil.java:189[m)
[[1;34mINFO[m] Stopping server on 35507
[[1;34mINFO[m] Stopping server on 35367
[[1;34mINFO[m] Stopping IPC Server listener on 0
[[1;34mINFO[m] Yielding from election
[[1;34mINFO[m] Yielding from election
[[1;34mINFO[m] Stopping IPC Server Responder
[[1;34mINFO[m] Stopping IPC Server Responder
[[1;34mINFO[m] Stopping IPC Server listener on 0
[[1;34mINFO[m] Session: 0x1020c9466840008 closed
[[1;34mINFO[m] Stopping HealthMonitor thread
[[1;33mWARNING[m] Ignoring stale result from old client with sessionId 0x1020c9466840008
[[1;34mINFO[m] EventThread shut down for session: 0x1020c9466840008
[[1;34mINFO[m] Session: 0x1020c9466840006 closed
[[1;34mINFO[m] Stopping HealthMonitor thread
[[1;33mWARNING[m] Ignoring stale result from old client with sessionId 0x1020c9466840006
[[1;33mWARNING[m] Ignoring stale result from old client with sessionId 0x1020c9466840006
[[1;34mINFO[m] EventThread shut down for session: 0x1020c9466840006
[[1;34mINFO[m] tearDown starting
[[1;34mINFO[m] STOPPING server
[[1;34mINFO[m] ConnnectionExpirerThread interrupted
[[1;34mINFO[m] accept thread exitted run method
[[1;34mINFO[m] selector thread exitted run method
[[1;34mINFO[m] selector thread exitted run method
[[1;34mINFO[m] shutting down
[[1;34mINFO[m] Shutting down
[[1;34mINFO[m] Shutting down
[[1;34mINFO[m] Shutting down
[[1;34mINFO[m] PrepRequestProcessor exited loop!
[[1;34mINFO[m] SyncRequestProcessor exited!
[[1;34mINFO[m] shutdown of request processor complete
[[1;34mINFO[m] connecting to 127.0.0.1 63074
[[1;34mINFO[m] SUCCEEDED testGracefulFailoverMultipleZKfcsFuzz
[[1;34mINFO[m] FINISHED testGracefulFailoverMultipleZKfcsFuzz
[JQF] After pre round flag = false
[JQF] After preRound mapping size = 62
[[1;34mINFO[m] Session: 0x1020c9466840009 closed
[[1;34mINFO[m] Stopping HealthMonitor thread
[[1;33mWARNING[m] Ignoring stale result from old client with sessionId 0x1020c9466840009
[[1;33mWARNING[m] Ignoring stale result from old client with sessionId 0x1020c9466840009
[[1;34mINFO[m] EventThread shut down for session: 0x1020c9466840009
[[1;34mINFO[m] Using port 11193
[[1;34mINFO[m] STARTING testGracefulFailoverMultipleZKfcsFuzz
[[1;34mINFO[m] STARTING server
[[1;34mINFO[m] zookeeper.snapshot.trust.empty : false
[[1;34mINFO[m] zookeeper.snapshotSizeFactor = 0.33
[[1;34mINFO[m] minSessionTimeout set to 6000
[[1;34mINFO[m] maxSessionTimeout set to 60000
[[1;34mINFO[m] Created server with tickTime 3000 minSessionTimeout 6000 maxSessionTimeout 60000 datadir /home/shuai/xlab/cfuzz/fuzz-hadoop/hadoop-common-project/hadoop-common/target/test/data/test11495346207453540865.junit.dir/version-2 snapdir /home/shuai/xlab/cfuzz/fuzz-hadoop/hadoop-common-project/hadoop-common/target/test/data/test11495346207453540865.junit.dir/version-2
[[1;34mINFO[m] Using org.apache.zookeeper.server.NIOServerCnxnFactory as server connection factory
[[1;34mINFO[m] Configuring NIO connection handler with 10s sessionless connection timeout, 2 selector thread(s), 32 worker threads, and 64 kB direct buffers.
[[1;34mINFO[m] binding to port 0.0.0.0/0.0.0.0:11193
[[1;34mINFO[m] Snapshotting: 0x0 to /home/shuai/xlab/cfuzz/fuzz-hadoop/hadoop-common-project/hadoop-common/target/test/data/test11495346207453540865.junit.dir/version-2/snapshot.0
[[1;34mINFO[m] Snapshotting: 0x0 to /home/shuai/xlab/cfuzz/fuzz-hadoop/hadoop-common-project/hadoop-common/target/test/data/test11495346207453540865.junit.dir/version-2/snapshot.0
[[1;34mINFO[m] connecting to 127.0.0.1 11193
[[1;34mINFO[m] Processing stat command from /127.0.0.1:55318
[[1;34mINFO[m] Stat command output
[[1;34mINFO[m] Client test setup finished
[[1;34mINFO[m] Initiating client connection, connectString=127.0.0.1:11193 sessionTimeout=54622836 watcher=org.apache.hadoop.ha.ActiveStandbyElector$WatcherWithClientRef@6e39345c
[[1;34mINFO[m] jute.maxbuffer value is 4194304 Bytes
[[1;34mINFO[m] zookeeper.request.timeout value is 0. feature enabled=
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:11193. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket connection established, initiating session, client: /127.0.0.1:55320, server: localhost/127.0.0.1:11193
[[1;34mINFO[m] Creating new log file: log.1
[[1;34mINFO[m] Session establishment complete on server localhost/127.0.0.1:11193, sessionid = 0x1020c9473a40000, negotiated timeout = 60000
[[1;34mINFO[m] Session connected.
[[1;34mINFO[m] got auth packet /127.0.0.1:55320
[[1;34mINFO[m] auth success /127.0.0.1:55320
[[1;34mINFO[m] Successfully created /shuai/dummy-cluster in ZK.
[[1;34mINFO[m] Session: 0x1020c9473a40000 closed
[[1;34mINFO[m] Waiting for svc0 to enter active state
[[1;33mWARNING[m] Ignoring stale result from old client with sessionId 0x1020c9473a40000
[[1;34mINFO[m] EventThread shut down for session: 0x1020c9473a40000
[[1;34mINFO[m] Initiating client connection, connectString=127.0.0.1:11193 sessionTimeout=54622836 watcher=org.apache.hadoop.ha.ActiveStandbyElector$WatcherWithClientRef@586a7f3
[[1;34mINFO[m] jute.maxbuffer value is 4194304 Bytes
[[1;34mINFO[m] zookeeper.request.timeout value is 0. feature enabled=
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:11193. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket connection established, initiating session, client: /127.0.0.1:55324, server: localhost/127.0.0.1:11193
[[1;34mINFO[m] Session establishment complete on server localhost/127.0.0.1:11193, sessionid = 0x1020c9473a40001, negotiated timeout = 60000
[[1;34mINFO[m] Session connected.
[[1;34mINFO[m] got auth packet /127.0.0.1:55324
[[1;34mINFO[m] auth success /127.0.0.1:55324
[[1;34mINFO[m] ZKFC RpcServer binding to 0.0.0.0/0.0.0.0:0
[[1;34mINFO[m] Using callQueue: class java.util.concurrent.LinkedBlockingQueue, queueCapacity: 300, scheduler: class org.apache.hadoop.ipc.DefaultRpcScheduler, ipcBackoff: false.
[[1;34mINFO[m] Starting Socket Reader #1 for port 0
[[1;34mINFO[m] IPC Server Responder: starting
[[1;34mINFO[m] IPC Server listener on 0: starting
[[1;34mINFO[m] Entering state SERVICE_HEALTHY
[[1;34mINFO[m] Local service DummyHAService #1 entered state: SERVICE_HEALTHY
[[1;34mINFO[m] Checking for any old active which needs to be fenced...
[[1;34mINFO[m] No old node to fence
[[1;34mINFO[m] Writing znode /shuai/dummy-cluster/ActiveBreadCrumb to indicate that the local node is the most recent active...
[[1;34mINFO[m] Trying to make DummyHAService #1 active...
[[1;34mINFO[m] Successfully transitioned DummyHAService #1 to active state
[[1;34mINFO[m] Adding svc1
[[1;34mINFO[m] Initiating client connection, connectString=127.0.0.1:11193 sessionTimeout=54622836 watcher=org.apache.hadoop.ha.ActiveStandbyElector$WatcherWithClientRef@457a962
[[1;34mINFO[m] jute.maxbuffer value is 4194304 Bytes
[[1;34mINFO[m] zookeeper.request.timeout value is 0. feature enabled=
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:11193. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket connection established, initiating session, client: /127.0.0.1:55332, server: localhost/127.0.0.1:11193
[[1;34mINFO[m] Session establishment complete on server localhost/127.0.0.1:11193, sessionid = 0x1020c9473a40002, negotiated timeout = 60000
[[1;34mINFO[m] Session connected.
[[1;34mINFO[m] got auth packet /127.0.0.1:55332
[[1;34mINFO[m] auth success /127.0.0.1:55332
[[1;34mINFO[m] ZKFC RpcServer binding to 0.0.0.0/0.0.0.0:0
[[1;34mINFO[m] Using callQueue: class java.util.concurrent.LinkedBlockingQueue, queueCapacity: 300, scheduler: class org.apache.hadoop.ipc.DefaultRpcScheduler, ipcBackoff: false.
[[1;34mINFO[m] Starting Socket Reader #1 for port 0
[[1;34mINFO[m] IPC Server Responder: starting
[[1;34mINFO[m] IPC Server listener on 0: starting
[[1;34mINFO[m] Entering state SERVICE_HEALTHY
[[1;34mINFO[m] Local service DummyHAService #2 entered state: SERVICE_HEALTHY
[[1;34mINFO[m] ZK Election indicated that DummyHAService #2 should become standby
[[1;34mINFO[m] Successfully transitioned DummyHAService #2 to standby state
[[1;34mINFO[m] Adding svc2
[[1;34mINFO[m] Initiating client connection, connectString=127.0.0.1:11193 sessionTimeout=54622836 watcher=org.apache.hadoop.ha.ActiveStandbyElector$WatcherWithClientRef@674d449a
[[1;34mINFO[m] jute.maxbuffer value is 4194304 Bytes
[[1;34mINFO[m] zookeeper.request.timeout value is 0. feature enabled=
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:11193. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket connection established, initiating session, client: /127.0.0.1:55334, server: localhost/127.0.0.1:11193
[[1;34mINFO[m] Session establishment complete on server localhost/127.0.0.1:11193, sessionid = 0x1020c9473a40003, negotiated timeout = 60000
[[1;34mINFO[m] Session connected.
[[1;34mINFO[m] got auth packet /127.0.0.1:55334
[[1;34mINFO[m] auth success /127.0.0.1:55334
[[1;34mINFO[m] ZKFC RpcServer binding to 0.0.0.0/0.0.0.0:0
[[1;34mINFO[m] Using callQueue: class java.util.concurrent.LinkedBlockingQueue, queueCapacity: 300, scheduler: class org.apache.hadoop.ipc.DefaultRpcScheduler, ipcBackoff: false.
[[1;34mINFO[m] Starting Socket Reader #1 for port 0
[[1;34mINFO[m] IPC Server Responder: starting
[[1;34mINFO[m] IPC Server listener on 0: starting
[[1;34mINFO[m] Entering state SERVICE_HEALTHY
[[1;34mINFO[m] Local service DummyHAService #3 entered state: SERVICE_HEALTHY
[[1;34mINFO[m] ZK Election indicated that DummyHAService #3 should become standby
[[1;34mINFO[m] Successfully transitioned DummyHAService #3 to standby state
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] SessionTrackerImpl exited loop!
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Initiating client connection, connectString=127.0.0.1:63074 sessionTimeout=10000 watcher=org.apache.hadoop.ha.ActiveStandbyElector$WatcherWithClientRef@49e0baa2
[[1;34mINFO[m] jute.maxbuffer value is 4194304 Bytes
[[1;34mINFO[m] zookeeper.request.timeout value is 0. feature enabled=
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Initiating client connection, connectString=127.0.0.1:63074 sessionTimeout=10000 watcher=org.apache.hadoop.ha.ActiveStandbyElector$WatcherWithClientRef@1c4fd9f4
[[1;34mINFO[m] jute.maxbuffer value is 4194304 Bytes
[[1;34mINFO[m] zookeeper.request.timeout value is 0. feature enabled=
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Initiating client connection, connectString=127.0.0.1:63074 sessionTimeout=10000 watcher=org.apache.hadoop.ha.ActiveStandbyElector$WatcherWithClientRef@b2933b8
[[1;34mINFO[m] jute.maxbuffer value is 4194304 Bytes
[[1;34mINFO[m] zookeeper.request.timeout value is 0. feature enabled=
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;31mERROR[m] Connection timed out: couldn't connect to ZooKeeper in 10000 milliseconds
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;31mERROR[m] Connection timed out: couldn't connect to ZooKeeper in 10000 milliseconds
[[1;34mINFO[m] Session: 0x0 closed
[[1;33mWARNING[m] org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
[[1;34mINFO[m] Session: 0x0 closed
[[1;33mWARNING[m] org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;31mERROR[m] Connection timed out: couldn't connect to ZooKeeper in 10000 milliseconds
[[1;34mINFO[m] Session: 0x0 closed
[[1;33mWARNING[m] org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Initiating client connection, connectString=127.0.0.1:63074 sessionTimeout=10000 watcher=org.apache.hadoop.ha.ActiveStandbyElector$WatcherWithClientRef@d4e6f9e
[[1;34mINFO[m] jute.maxbuffer value is 4194304 Bytes
[[1;34mINFO[m] zookeeper.request.timeout value is 0. feature enabled=
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Initiating client connection, connectString=127.0.0.1:63074 sessionTimeout=10000 watcher=org.apache.hadoop.ha.ActiveStandbyElector$WatcherWithClientRef@3d5d2c80
[[1;34mINFO[m] jute.maxbuffer value is 4194304 Bytes
[[1;34mINFO[m] zookeeper.request.timeout value is 0. feature enabled=
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Initiating client connection, connectString=127.0.0.1:63074 sessionTimeout=10000 watcher=org.apache.hadoop.ha.ActiveStandbyElector$WatcherWithClientRef@7b9490a6
[[1;34mINFO[m] jute.maxbuffer value is 4194304 Bytes
[[1;34mINFO[m] zookeeper.request.timeout value is 0. feature enabled=
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;31mERROR[m] Connection timed out: couldn't connect to ZooKeeper in 10000 milliseconds
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;31mERROR[m] Connection timed out: couldn't connect to ZooKeeper in 10000 milliseconds
[[1;34mINFO[m] Session: 0x0 closed
[[1;33mWARNING[m] org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
[[1;34mINFO[m] Session: 0x0 closed
[[1;33mWARNING[m] org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;31mERROR[m] Connection timed out: couldn't connect to ZooKeeper in 10000 milliseconds
[[1;34mINFO[m] Session: 0x0 closed
[[1;33mWARNING[m] org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Initiating client connection, connectString=127.0.0.1:63074 sessionTimeout=10000 watcher=org.apache.hadoop.ha.ActiveStandbyElector$WatcherWithClientRef@164aa27d
[[1;34mINFO[m] jute.maxbuffer value is 4194304 Bytes
[[1;34mINFO[m] zookeeper.request.timeout value is 0. feature enabled=
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Initiating client connection, connectString=127.0.0.1:63074 sessionTimeout=10000 watcher=org.apache.hadoop.ha.ActiveStandbyElector$WatcherWithClientRef@3913f57c
[[1;34mINFO[m] jute.maxbuffer value is 4194304 Bytes
[[1;34mINFO[m] zookeeper.request.timeout value is 0. feature enabled=
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Initiating client connection, connectString=127.0.0.1:63074 sessionTimeout=10000 watcher=org.apache.hadoop.ha.ActiveStandbyElector$WatcherWithClientRef@5abeceba
[[1;34mINFO[m] jute.maxbuffer value is 4194304 Bytes
[[1;34mINFO[m] zookeeper.request.timeout value is 0. feature enabled=
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;31mERROR[m] Connection timed out: couldn't connect to ZooKeeper in 10000 milliseconds
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;31mERROR[m] Connection timed out: couldn't connect to ZooKeeper in 10000 milliseconds
[[1;34mINFO[m] Session: 0x0 closed
[[1;33mWARNING[m] org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
[[1;34mINFO[m] Session: 0x0 closed
[[1;33mWARNING[m] org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;31mERROR[m] Connection timed out: couldn't connect to ZooKeeper in 10000 milliseconds
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Session: 0x0 closed
[[1;33mWARNING[m] org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;31mERROR[m] Failed to reEstablish connection with ZooKeeper
[[1;31mERROR[m] Fatal error occurred:Failed to reEstablish connection with ZooKeeper
[[1;33mWARNING[m] Ignoring stale result from old client with sessionId 0x00000000
[[1;34mINFO[m] EventThread shut down for session: 0x0
[[1;33mWARNING[m] Ignoring stale result from old client with sessionId 0x00000000
[[1;34mINFO[m] EventThread shut down for session: 0x0
[[1;33mWARNING[m] Ignoring stale result from old client with sessionId 0x00000000
[[1;34mINFO[m] EventThread shut down for session: 0x0
[[1;34mINFO[m] Initiating client connection, connectString=127.0.0.1:63074 sessionTimeout=10000 watcher=org.apache.hadoop.ha.ActiveStandbyElector$WatcherWithClientRef@271afd0c
[[1;34mINFO[m] jute.maxbuffer value is 4194304 Bytes
[[1;34mINFO[m] zookeeper.request.timeout value is 0. feature enabled=
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;31mERROR[m] Failed to reEstablish connection with ZooKeeper
[[1;31mERROR[m] Fatal error occurred:Failed to reEstablish connection with ZooKeeper
[[1;33mWARNING[m] Ignoring stale result from old client with sessionId 0x00000000
[[1;34mINFO[m] EventThread shut down for session: 0x0
[[1;33mWARNING[m] Ignoring stale result from old client with sessionId 0x00000000
[[1;34mINFO[m] EventThread shut down for session: 0x0
[[1;33mWARNING[m] Ignoring stale result from old client with sessionId 0x00000000
[[1;34mINFO[m] EventThread shut down for session: 0x0
[[1;34mINFO[m] Initiating client connection, connectString=127.0.0.1:63074 sessionTimeout=10000 watcher=org.apache.hadoop.ha.ActiveStandbyElector$WatcherWithClientRef@35ee9c74
[[1;34mINFO[m] jute.maxbuffer value is 4194304 Bytes
[[1;34mINFO[m] zookeeper.request.timeout value is 0. feature enabled=
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;31mERROR[m] Failed to reEstablish connection with ZooKeeper
[[1;31mERROR[m] Fatal error occurred:Failed to reEstablish connection with ZooKeeper
[[1;33mWARNING[m] Ignoring stale result from old client with sessionId 0x00000000
[[1;34mINFO[m] EventThread shut down for session: 0x0
[[1;33mWARNING[m] Ignoring stale result from old client with sessionId 0x00000000
[[1;34mINFO[m] EventThread shut down for session: 0x0
[[1;33mWARNING[m] Ignoring stale result from old client with sessionId 0x00000000
[[1;34mINFO[m] EventThread shut down for session: 0x0
[[1;34mINFO[m] Initiating client connection, connectString=127.0.0.1:63074 sessionTimeout=10000 watcher=org.apache.hadoop.ha.ActiveStandbyElector$WatcherWithClientRef@41cbace
[[1;34mINFO[m] jute.maxbuffer value is 4194304 Bytes
[[1;34mINFO[m] zookeeper.request.timeout value is 0. feature enabled=
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;31mERROR[m] Connection timed out: couldn't connect to ZooKeeper in 10000 milliseconds
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;31mERROR[m] Connection timed out: couldn't connect to ZooKeeper in 10000 milliseconds
[[1;34mINFO[m] Session: 0x0 closed
[[1;33mWARNING[m] org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
[[1;34mINFO[m] Session: 0x0 closed
[[1;33mWARNING[m] org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;31mERROR[m] Connection timed out: couldn't connect to ZooKeeper in 10000 milliseconds
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Session: 0x0 closed
[[1;33mWARNING[m] org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Initiating client connection, connectString=127.0.0.1:63074 sessionTimeout=10000 watcher=org.apache.hadoop.ha.ActiveStandbyElector$WatcherWithClientRef@6a48115f
[[1;34mINFO[m] jute.maxbuffer value is 4194304 Bytes
[[1;34mINFO[m] zookeeper.request.timeout value is 0. feature enabled=
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Initiating client connection, connectString=127.0.0.1:63074 sessionTimeout=10000 watcher=org.apache.hadoop.ha.ActiveStandbyElector$WatcherWithClientRef@5234959b
[[1;34mINFO[m] jute.maxbuffer value is 4194304 Bytes
[[1;34mINFO[m] zookeeper.request.timeout value is 0. feature enabled=
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Initiating client connection, connectString=127.0.0.1:63074 sessionTimeout=10000 watcher=org.apache.hadoop.ha.ActiveStandbyElector$WatcherWithClientRef@2f2dc9ab
[[1;34mINFO[m] jute.maxbuffer value is 4194304 Bytes
[[1;34mINFO[m] zookeeper.request.timeout value is 0. feature enabled=
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;31mERROR[m] Connection timed out: couldn't connect to ZooKeeper in 10000 milliseconds
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;31mERROR[m] Connection timed out: couldn't connect to ZooKeeper in 10000 milliseconds
[[1;34mINFO[m] Session: 0x0 closed
[[1;33mWARNING[m] org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
[[1;34mINFO[m] Session: 0x0 closed
[[1;33mWARNING[m] org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;31mERROR[m] Connection timed out: couldn't connect to ZooKeeper in 10000 milliseconds
[[1;34mINFO[m] Session: 0x0 closed
[[1;33mWARNING[m] org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Initiating client connection, connectString=127.0.0.1:63074 sessionTimeout=10000 watcher=org.apache.hadoop.ha.ActiveStandbyElector$WatcherWithClientRef@3809ddc0
[[1;34mINFO[m] jute.maxbuffer value is 4194304 Bytes
[[1;34mINFO[m] zookeeper.request.timeout value is 0. feature enabled=
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Initiating client connection, connectString=127.0.0.1:63074 sessionTimeout=10000 watcher=org.apache.hadoop.ha.ActiveStandbyElector$WatcherWithClientRef@714c049f
[[1;34mINFO[m] jute.maxbuffer value is 4194304 Bytes
[[1;34mINFO[m] zookeeper.request.timeout value is 0. feature enabled=
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Initiating client connection, connectString=127.0.0.1:63074 sessionTimeout=10000 watcher=org.apache.hadoop.ha.ActiveStandbyElector$WatcherWithClientRef@3c2ef08d
[[1;34mINFO[m] jute.maxbuffer value is 4194304 Bytes
[[1;34mINFO[m] zookeeper.request.timeout value is 0. feature enabled=
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;31mERROR[m] Connection timed out: couldn't connect to ZooKeeper in 10000 milliseconds
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;31mERROR[m] Connection timed out: couldn't connect to ZooKeeper in 10000 milliseconds
[[1;34mINFO[m] Session: 0x0 closed
[[1;33mWARNING[m] org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Socket error occurred: localhost/127.0.0.1:63074: Connection refused
[[1;31mERROR[m] Connection timed out: couldn't connect to ZooKeeper in 10000 milliseconds
[[1;34mINFO[m] Session: 0x0 closed
[[1;33mWARNING[m] org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Opening socket connection to server localhost/127.0.0.1:63074. Will not attempt to authenticate using SASL (unknown error)
[[1;34mINFO[m] Session: 0x0 closed
[[1;33mWARNING[m] org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;31mERROR[m] Failed to reEstablish connection with ZooKeeper
[[1;31mERROR[m] Fatal error occurred:Failed to reEstablish connection with ZooKeeper
[[1;33mWARNING[m] Ignoring stale result from old client with sessionId 0x00000000
[[1;34mINFO[m] EventThread shut down for session: 0x0
[[1;33mWARNING[m] Ignoring stale result from old client with sessionId 0x00000000
[[1;34mINFO[m] EventThread shut down for session: 0x0
[[1;33mWARNING[m] Ignoring stale result from old client with sessionId 0x00000000
[[1;34mINFO[m] EventThread shut down for session: 0x0
[[1;34mINFO[m] Cur data: no node
[[1;31mERROR[m] Failed to reEstablish connection with ZooKeeper
[[1;31mERROR[m] Fatal error occurred:Failed to reEstablish connection with ZooKeeper
[[1;33mWARNING[m] Ignoring stale result from old client with sessionId 0x00000000
[[1;34mINFO[m] EventThread shut down for session: 0x0
[[1;33mWARNING[m] Ignoring stale result from old client with sessionId 0x00000000
[[1;34mINFO[m] EventThread shut down for session: 0x0
[[1;33mWARNING[m] Ignoring stale result from old client with sessionId 0x00000000
[[1;34mINFO[m] EventThread shut down for session: 0x0
[[1;34mINFO[m] Cur data: no node
[[1;31mERROR[m] Failed to reEstablish connection with ZooKeeper
[[1;31mERROR[m] Fatal error occurred:Failed to reEstablish connection with ZooKeeper
[[1;33mWARNING[m] Ignoring stale result from old client with sessionId 0x00000000
[[1;34mINFO[m] EventThread shut down for session: 0x0
[[1;33mWARNING[m] Ignoring stale result from old client with sessionId 0x00000000
[[1;34mINFO[m] EventThread shut down for session: 0x0
[[1;33mWARNING[m] Ignoring stale result from old client with sessionId 0x00000000
[[1;34mINFO[m] EventThread shut down for session: 0x0
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;34mINFO[m] Cur data: no node
[[1;31mERROR[m] The failover controller encounters runtime error: 
[[1;31mE[1;31mjava.lang.InterruptedException[mRROR[m] The failover controller encounters runtime e
rror: 
[[[1;311mja;va.lang.InterruptedException    [m[
1mat[m31mERROR ja va.lang.Object.wait[ ([1mNative Method[m) 
      [1mat[mm] The failover controller encounters runti mej aeva.lang.Object.wait[1mat[m java (.lang.Objerctr.or:wait[ ([1mNative Method [m)1
mObject.java:328[m)

        [[1;34mINFO[m] FAILED testGracefulFailoverMultipleZKfcsFuzz
[1mat[m j[ava.lang.Object.wait[1;31morg.junit.runners.model.Test ([1mObject.java:328[m)
    [1mat[m org.apache.hadoop.ha.ZKFailoverController.mainLoop[1;3 ([1mZKFailoverController.java:389[m)T
imedOutException[m1ma t[m1 org .a  m[1mat[m org.apache.hadoop.ha.ZKFailoverController.doRunp ([1mZKFailoverController.java:253[m): 
    a[1mat[m org.apache.hadoop.ha.ZKFailoverController.[1;31mtejsavat.l tiamed out after 180000 milliseconds[mc
he.hadoop.ha.ZKcFailoveang.InrteContro    cess$000[1mat[mller. ([1mZKFailoverController.javra:63[m)
    [1mat[m org.apache.hadoop.ha.ZKFailoverController$1.runmainL ([1mZKFailoverController.java:181[m) 
    [1mat[mo org.apache.hadoop.ha.ZKFailoverController$1.runrupte ([1mZKFailoverController.java:177[m)
    [1mat[m org.apache.hadoop.security.SecurityUtil.doAsLoginUserOrFatalop ([1mSecurityUtil.ja ([1mZKFailoverController.jjava:389[m)v
a:503[m)
    dException[m 
   [1mat[ma org    [[1mat[m java.lang.Object.wait. ([1mNative Methovd[m)
    [1mat[m java.lang.Object.waitapac1he.hadoop.h ([1mObject.aj.lang.Thread.sleep ([1mNative Method[m)
    a[1mat[mm org.apache.hadoop.ha.ActiveStandbyElectorTestUtil.waitForActiveLockData.ZKFailoverController.doRunava:328[ (m) 
  (  [1m[1ActiveStandbyElectorTestUtil.java:68[m)a
t[m org.apache.hadoop.ha.ZKFailoverController.runmat[m ([1mZKFailoverController.java:177[m)
    [1mZKFailoverC oorg.apache.hadoo p. ha.ZKFailoverController.mainLoopntroller. ([1mZKFailoverController.java:389[m)
[    j[1mat[m org.apache.ha  d[1mat[m org.apache.hadoop.ha.MiniZKFCCluster.waitForActiveLockHolderava:253[ m([1mMiniZKFCCluster.java:260[m)
    1mat[m org.apache.hadoop.ha.MiniZKFCCluster$DummyZKFCThread.doWork[1mat[m) or g.apachoeop.ha.ZKFailoverCon(troller.doRun
    [1.hadoop.ha.TestZKFailoverController.testGracefulFailoverMultipleZKmfat[m org.apache.hadoop.ha.ZKFailoverController.access$000[1mMiniZKFCCluster.java:301[m)
     [1mat[m org.apache.hadoop.test.MultithreadedTestUtil$TestingThread.run ([1 ([1mMultithreadedTestUtil.java:189[m)
csFuzzmZKFailover ([1mTest(Z[1mZKFailoverController.java:253[m)
    C[1mat[m org.apache.hadoop.ha.ZKFailoverController.a[c[1;34mINFO[m] Stopping server on 44411ontroller.java:63[m)K
FailoverController.java:657[m)

    [1matc[emss$000     jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 ([1mNa ([1mZKFailoverController.java:63[m)t
i[[1;34mINFO[m] Stop[1mat[mp org.apache.hadoop.ha.ZKFailoverContrve Method[m)    
[1mat[mo ller$1.runing IPC Serv ([1mZKFaiorg.apache.hadoop.ha.ZKFailoverController$1.run    loverController.java:181[m)
er li ([1mZKFailoverController.java:181[m)
     [1mat[m  org.apache.hadoop.ha.ZKFailoverController$1.runste n([1mZKFailoverController.java:177[m)
      [1mat[m[ org.apache.hadoop.ha.ZKFailoverController$1.run[1mat[m org.ap ([1mZKFailoverController.java:1er on 07
7[m)
    a[[1;34mINFO[m] Yielding from election1
mat[mc[[1;34mINFO[m] Stopping IPC Server Responder
[1mat[m org.apache.hadoop.security.SecurityUtil.doAsLoginUserOrFahe.hadoop.security.SecurityUtil.doAsLogi nUserOrFataltaljdk.internal.reflect.NativeMethodAccessorImpl.invoke ([1mSecurityUti ([1mNativeMethodAccessorImpl.java:62[m)
  ([1mSecurityUtil.java:503[ml.java:503[m)
)       
[[1mat[m  jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke1mat[m    org.apach ([1mDelegatingMethodAccess[1mat[m org.apache.hadoop.ha.ZKFailoverController.rune.hado ([1mZKFailoverController.java:177[m)
    o[1rmat[mo org.apache.hadoop.ha.MiniZKFCClIuster$DummyZKFCThread.doWorkp.ha. ([1mMiniZKFCCluster.java:301[m)
    mpl.java:43[m)Z
KFailoverController.run[1mat[m     ([1mZKFailoverController.java:177[m)
     [[1mat[mo rg.apache.had1mat[moop.test.MultithreadedTestUtil$TestingThread.runorg.apache.hadoop.ha.MiniZKFCCluster$DummyZKFCThread.doWork ([1mMultithreadedTestUtil.java:189[m)
 ([1mMiniZKFCCluster.java:301[m)
    [1mat[m org.apache.hadoop.test.MultithreadedTestUtil$TestingThread.r[[1;34mINFO[m] Stopping server on 34653
un ([1mMultithreadedTestUtil.java:189[m)
 java.lang.reflect.Method.invoke[[1;34mINFO[m] Stopping server on 45171
 ([1mMethod.java:566[m)[[1;34mINFO[m] Stopping IPC Server listener on 0

    [[1;34mINFO[m] Stopping IPC Server Responder
[1mat[[[1;34mINFO[m] Yielding from election
m org.junit.runners.model.FrameworkMethod$1.runReflectiveCall[[1;34mINFO[m] Stopping IPC Server listener on 0 ([1mFrameworkMethod.java:59[m)

    [[1mat[m org.juni[1;34mINFO[m] Yielding from electiont.internal.runn
ers.model.Re[[1;34mINFO[m] Stopping IPC Server Responderf
lectiveCallable.run ([1mReflectiveCallable.java:12[m)
    [1mat[m org.junit.runners.model.FrameworkMethod.invokeExplosively ([1mFrameworkMethod.java:56[m)
    [1mat[m edu.berkeley.cs.jqf.fuzz.junit.TrialRunner$1.evaluate ([1mTrialRunner.java:59[m)
    [1mat[m org.junit.internal.runners.statements.RunBefores.evaluate ([1mRunBefores.java:26[m)
    [1mat[m org.junit.internal.runners.statements.RunAfters.evaluate ([1mRunAfters.java:27[m)
    [1mat[m org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call ([1mFailOnTimeout.java:288[m)
    [1mat[m org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call ([1mFailOnTimeout.java:282[m)
    [1mat[m java.util.concurrent.FutureTask.run ([1mFutureTask.java:264[m)
    [1mat[m java.lang.Thread.run ([1mThread.java:829[m)
[[1;34mINFO[m] FINISHED testGracefulFailoverMultipleZKfcsFuzz
[[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[[1;34mINFO[m] [1;31mBUILD FAILURE[m
[[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[[1;34mINFO[m] Total time:  03:05 min
[[1;34mINFO[m] Finished at: 2022-10-16T17:46:42-05:00
[[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[[1;31mERROR[m] Failed to execute goal [32medu.berkeley.cs.jqf:jqf-maven-plugin:2.0-SNAPSHOT:fuzz[m [1m(default-cli)[m on project [36mhadoop-common[m: [1;31mFuzzing resulted in the test failing on 1 input(s). Possible bugs found. Use mvn jqf:repro to reproduce failing test cases from /home/shuai/xlab/cfuzz/fuzz-hadoop/hadoop-common-project/hadoop-common/fuzz_output_round2/fuzz-results/org.apache.hadoop.ha.TestZKFailoverController/testGracefulFailoverMultipleZKfcsFuzz/failures. Sample exception included with this message.[m: test timed out after 180000 milliseconds -> [1m[Help 1][m
[[1;31mERROR[m] 
[[1;31mERROR[m] To see the full stack trace of the errors, re-run Maven with the [1m-e[m switch.
[[1;31mERROR[m] Re-run Maven using the [1m-X[m switch to enable full debug logging.
[[1;31mERROR[m] 
[[1;31mERROR[m] For more information about the errors and possible solutions, please read the following articles:
[[1;31mERROR[m] [1m[Help 1][m http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
