Found crash: class java.lang.RuntimeException - Deferred
Saved - /home/shuai/xlab/cfuzz/fuzz-hadoop/hadoop-common-project/hadoop-common/fuzz_output_round3/fuzz-results/org.apache.hadoop.ha.TestZKFailoverController/testGracefulFailoverMultipleZKfcs/failures/id_000000 random +crash
Saving new input (at run 2): input #0 of size 224; reason = +count +cov +valid
Saved - /home/shuai/xlab/cfuzz/fuzz-hadoop/hadoop-common-project/hadoop-common/fuzz_output_round3/fuzz-results/org.apache.hadoop.ha.TestZKFailoverController/testGracefulFailoverMultipleZKfcs/corpus/id_000000 random +count +cov +valid
Found crash: class org.junit.runners.model.TestTimedOutException - test timed out after 180000 milliseconds
Saved - /home/shuai/xlab/cfuzz/fuzz-hadoop/hadoop-common-project/hadoop-common/fuzz_output_round3/fuzz-results/org.apache.hadoop.ha.TestZKFailoverController/testGracefulFailoverMultipleZKfcs/failures/id_000001 src:000000,havoc:25 +crash
Found crash: class java.io.IOException - Couldn't create /shuai/dummy-cluster
Saved - /home/shuai/xlab/cfuzz/fuzz-hadoop/hadoop-common-project/hadoop-common/fuzz_output_round3/fuzz-results/org.apache.hadoop.ha.TestZKFailoverController/testGracefulFailoverMultipleZKfcs/failures/id_000002 src:000000,havoc:4 +crash
Found crash: class java.io.IOException - Couldn't create /shuai/dummy-cluster
Saved - /home/shuai/xlab/cfuzz/fuzz-hadoop/hadoop-common-project/hadoop-common/fuzz_output_round3/fuzz-results/org.apache.hadoop.ha.TestZKFailoverController/testGracefulFailoverMultipleZKfcs/failures/id_000003 src:000000,havoc:3 +crash
Found crash: class org.junit.runners.model.TestTimedOutException - test timed out after 180000 milliseconds
Saved - /home/shuai/xlab/cfuzz/fuzz-hadoop/hadoop-common-project/hadoop-common/fuzz_output_round3/fuzz-results/org.apache.hadoop.ha.TestZKFailoverController/testGracefulFailoverMultipleZKfcs/failures/id_000004 src:000000,havoc:27 +crash
Found crash: class org.junit.runners.model.TestTimedOutException - test timed out after 180000 milliseconds
Saved - /home/shuai/xlab/cfuzz/fuzz-hadoop/hadoop-common-project/hadoop-common/fuzz_output_round3/fuzz-results/org.apache.hadoop.ha.TestZKFailoverController/testGracefulFailoverMultipleZKfcs/failures/id_000005 src:000000,havoc:2 +crash
